#! /bin/bash

# Lint files as Verilog-2001, finding submodules as needed in whole Parts repo

ALL_FILES=$@

# Where is this repo located (absolute path)
GIT_ROOT=$(git rev-parse --show-toplevel)

# Find all directories and prepend "-y" to each
SEARCH_DIRS=$(find ${GIT_ROOT}/Parts -type d -exec echo "-y" {} \;)

for FILE in ${ALL_FILES}
do
    verilator -Wall +1364-2001ext+v ${SEARCH_DIRS} --lint-only ${FILE}
done

