#! /bin/bash

set -x -e

TOP=DUT
EXEC=V${TOP}
LOGS=${PWD}/LOG
RUNS=RUN

# Where is this repo located (absolute path)
GIT_ROOT=$(git rev-parse --show-toplevel)

# Find all directories and prepend "-y" to each
SEARCH_DIRS=$(find ${GIT_ROOT}/Parts -type d -exec echo "-y" {} \;)

# Clean up
rm -rf obj_dir
rm ${LOGS}/*

# Check the code. A different number of warnings is a flag to check things.
verilator -Wall +1364-2001ext+v ${SEARCH_DIRS} --lint-only -cc ${TOP}.v &> ${LOGS}/LOG.lint

# Verilate the design and compile design library. Logfile should be empty!
verilator -trace -Wall +1364-2001ext+v ${SEARCH_DIRS} -cc ${TOP}.v --exe test_bench.cpp 2>&1 | tee ${LOGS}/LOG.verilate

# Compile into a test bench executable
pushd obj_dir
    make -j 4 -f ${EXEC}.mk 2>&1 | tee ${LOGS}/LOG.compile
popd

# Copy executable over, and run it
cp obj_dir/${EXEC} ${RUNS}/

pushd ${RUNS}
    time ./${EXEC} 2>&1 | tee ${LOGS}/LOG.output
popd


